### PR TITLE
Auto login after registering

### PR DESCRIPTION
**Pull request by abeltran1804**
Solves issue #15 
Also solves issue #25 
After register, redirects to "profile/username"

### CODE REVIEW

**Comment by aylinev2** [comment]
looks good to me! one thing though is to maybe redirect a user to the site's homepage instead of their profile page?

**Review by aylinev2 — COMMENTED** [review]
also I just noticed you fixed the bug with the user profile page not displaying if they have no messages! Good catch!

**Comment by abeltran1804** [comment]
Thanks! Just fixed it :)

**Review by aylinev2 — APPROVED** [review]
Looks good to me!

**Pull request merged**
